package com.example.fuktorial

object FuquotesInfo {
    val fuquotesList = listOf(
        "Fuck you",
        "You asshole",
        "Who the fuck are you anyway, :company, why are you stirring up so much trouble, and, who pays you?",
        "Fuck you, asshole",
        "This is Fucking Awesome",
        "Ey, back the fuck off",
        "Eat a bag of fucking dicks",
        "Fucking Bary is a fucking pussy. I'm going to fucking bury that guy, I have done it before, and I will do it again.",
        "Happy Fucking Birthday",
        "Why? Because fuck you, that's why",
        "Your head is as empty as a eunuch’s underpants. Fuck off!",
        "Please choke on a bucket of cocks.",
        "Christ on a bendy-bus, don't be such a fucking faff-arse.",
        "Fuckity bye!",
        "Can you use brain? Fuck no!",
        "Fuck me gently with a chainsaw. Do I look like Mother Teresa?",
        "Fuck off, you worthless cocksplat",
        "Cool story, bro.",
        "How about a nice cup of shut the fuck up?",
        "You're a fucking problem solving super-hero.",
        "You are being the usual slimy hypocritical asshole... You may have had value ten years ago, but people will see that you don't anymore",
        "I'd love to stop and chat to you but I'd rather have type 2 diabetes",
        "Go and take a flying fuck at a rolling donut",
        "Do fucking something!",
        "Equity only? Long hours? Zero Pay? Well, just sign me right the fuck up.",
        "I can't fuckin' even",
        "Everyone can go and fuck off",
        "Fuck everything",
        "Fuck you, your whole family, your pets, and your feces",
        "Fascinating story, in what chapter do you shut the fuck up?",
        "Go fuck yourself :name, you'll disappoint fewer people",
        "And He said unto them, 'Verily, cast thine eyes upon the field in which I grow my fucks', and they gave witness unto the field, and saw that it was barren",
        "I don't give a flying fuck",
        "Fuck That, Fuck You",
        "Fuck that shit",
        "Fuck you, you fucking fuck",
        "Golf foxtrot yankee",
        "I give zero fucks",
        "I don't want to talk to you, no more, you empty-headed animal, food trough wiper. I fart in your general direction. Your mother was a hamster and your father smelt of elderberries. Now go away or I shall taunt you a second time",
        "Fuck you and the horse you rode in on",
        "That sounds like a fucking great idea!",
        "You can not imagine the immensity of the FUCK I do not give",
        "Fucking fuck off",
        "Fuck you, fuck me, fuck your family. Fuck your father, fuck your mother, fuck you and me",
        "Fuck off. And when you get there, fuck off from there too. Then fuck off some more. Keep fucking off until you get back here. Then fuck off again",
        "Keep the fuck calm and fuck",
        "Oh fuck off, just really fuck off you total dickface. Christ, you are fucking thick",
        "You're a fucking legend",
        "Fuck my life",
        "There aren't enough swear-words in the English language, so now I'll have to call you perkeleen vittupää just to express my disgust and frustration with this crap",
        "Check your fucking logs!",
        "Do I look like I give a fuck",
        "Looking for a fuck to give",
        "What you've just said is one of the most insanely idiotic things I have ever heard. At no point in your rambling, incoherent response were you even close to anything that could be considered a rational thought. Everyone in this room is now dumber for having listened to it. I award you no points, and may God have mercy on your soul",
        "Maybe. Maybe not. Maybe fuck yourself",
        "Fuck me.",
        "Happy fuckin' mornin'!",
        "No fucks given.",
        "Well, aren't you a shining example of a rancid fuck-nugget",
        "Fuck off",
        "Fuck off with this shit",
        "Why don't you go outside and play hide-and-go-fuck-yourself?",
        "Fuck this day in particular",
        "Well, fuck me pink",
        "What the fuck is your problem?",
        "Fuck you, I'm a programmer, bitch!",
        "To fuck off, or to fuck off (that is not a question)",
        "I don't give a rat's arse",
        "You Fucktard!",
        "That's fucking ridiculous",
        "You're a fucking Rock Star!",
        "Read the fucking manual!",
        "English, motherfucker, do you speak it?",
        "For Fuck's sake!",
        "Thou clay-brained guts, thou knotty-pated fool, thou whoreson obscene greasy tallow-catch!",
        "Fuck this shit!",
        "Shut the fuck up",
        "Not a single fuck was given",
        "Fuck you very much",
        "Fuck that",
        "You think I give a fuck?",
        "Hey, what the fuck were you actually thinking?",
        "Fuck this",
        "Who has two thumbs and doesn't give a fuck? You",
        "Thanks, fuck you too",
        "Come the fuck in or fuck the fuck off",
        "I don't waste my fucking time with your bullshit!",
        "What the fuck?",
        "Merry Fucking Christmas",
        "Ask me if I give a motherfuck?",
        "Zero, that's the number of fucks I give",
        "Happy New Fucking Year",
        "Fuck it and then fuck it more",
        "Fuck off, motherfucker",
        "Have a nice fuck",
        "Today is the day I don't give a fuck",
        "Fuck this and fuck that",
        "Fuck the buck",
        "Guess what? Fuck you",
        "You shall not fuck",
        "I hope you know you're a fucking idiot"
    )
}